Feature/#6 auth
paneiOS/RunToYou pull request #12
Opened 2024-05-08 06:52 UTC by qwe179

## #️⃣연관된 이슈

> #6 

## 📝작업 내용
> AppAuthViewController.swift 개발 
> 런치스크린 제약사항 전체화면에 맞게 수정 
> UIFont, UIColor extension 추가
> NotoSansKR 폰트 추가
> 앱 접근 권한 화면 사용 아이콘들 추가(bell.SVG, location_on.SVG, photo_camera.SVG, smartphone.SVG)

### 스크린샷 (선택)
![image](https://github.com/paneiOS/RunToYou/assets/50470014/44bbf9d8-6b1d-4248-a076-a7e745b5f8cc)
## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2024-05-08 13:59 UTC, paneiOS commented on RunToYou/AppDelegate.swift
> -
SwiftLint 룰에 의해 지우신것같은데 여백만 지우면 되는 부분입니다.
SwiftLint git에 가셔서 기본룰이 어떤게 있는지 그리고 이부분이 왜 생겼는지에 대해 한번 알아보시면 큰 도움될것같습니다.

2024-05-08 14:00 UTC, paneiOS commented on RunToYou/Extensions/UIColorExtension.swift
> +    static func getColor(hexString: String, alpha: CGFloat = 1.0) -> UIColor {
피그마에 rgba로 바로 볼수있을텐데 hex로 변환하는 함수를 만드는것은 낭비인것같습니다.
바로 UIColor(red: , green: , blue: , alpha: )로 쓸수있도록 수정하는건 어떨까요?

2024-05-08 14:02 UTC, paneiOS commented on RunToYou/Extensions/UIFontExtension.swift
> +    static func attributedTextWithTwoFonts(text1: String, font1: UIFont, text2: String, font2: UIFont) -> NSAttributedString {
사용하지 않는 함수로 보이는데 제거 하는게 좋을것같습니다.

2024-05-08 14:10 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +//  ViewController.swift
안바뀌었습니다.😅

2024-05-08 14:11 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    let titleLabel: UILabel = {
접근제어자 추가해주세요.

2024-05-08 14:16 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    required init?(coder: NSCoder) {
이거 한번 알아보기

2024-05-08 14:22 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +            $0.width.height.equalTo(24)
`$0.size.equalTo(24)`로 변경 가능합니다.

2024-05-08 14:22 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +            $0.leading.equalToSuperview()
`$0.centerY.leading. equalToSuperview()`로 사용 가능합니다.

2024-05-08 14:34 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +        nextButton.addTarget(self, action: #selector(goNextView), for: .touchUpInside)
RxCocoa에 있는 버튼 연결하는 함수가 있는데 그걸로 적용하시는게 어떨까요?

2024-05-08 14:39 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +            $0.trailing.equalTo(-15)
inset을 사용해주세요.

2024-05-08 14:56 UTC, paneiOS reviewed
코드리뷰 했는데 코멘트가 제법 있습니다.

2024-05-09 10:52 UTC, paneiOS commented on RunToYou/SceneDelegate.swift
>          window.rootViewController = UINavigationController(rootViewController: viewController)
네비게이션으로 시작하는데 네비게이션을 넣은 이유가 있을까요?

2024-05-09 10:55 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    private let disposeBag = DisposeBag()
UI 프로퍼티들을 먼저 배치하고 그다음 viewDodLoad 전에 UI 프로퍼티가 아닌애들을 위치시키는걸로 통일시켰으면 하는데 어떻게 생각하시나요?

2024-05-09 10:55 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +        setupDatas()
Data는 복수형입니다.

2024-05-09 10:58 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    private func setAddTarget() {
다른 함수들은 `setup-` 을 사용하였는데 이 함수만 `set-`을 사용하셨네요.
통일시켰으면 합니다.
저희 컨벤션에 get은 지양한다고 되어있는데 set도 지양하고 setup을 사용해도 될까요?

2024-05-09 10:58 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +                self?.goNextView()
weak self의 경우 guard문을 사용해도 될까요? 저번 코드리뷰와 동일한 내용입니다.

2024-05-09 10:59 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    private func goNextView() {
Todo 주석 사용하기로 했었는데 혹시 기억하시나요?

2024-05-09 11:01 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +        recordRowView.setupDatas(
데이터가 고정값이면 setupDagtas로 묶어서 처리하는것보다 각 UILabel 선언시에 하는게 더 좋았을것같습니다.

2024-05-09 11:01 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    private func setupLayout() {
한칸 띄어쓰기 부탁드립니다.

2024-05-09 11:02 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    deinit {
deinit은 init, viewDidLoad와 같이 놓는게 어떨까요 private함수 밑에 있으니까 잘 보이지 않네요.

2024-05-09 11:03 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    func setupDatas(image: UIImage, titleString: String, detailString: String, isOptional: Bool) {
isOprtional에 기본값을 준다면 사용시 코드라인을 줄일수있습니다.

2024-05-09 11:04 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +        }
한줄로 줄일수있습니다. 혹시 알고 계신가요?

2024-05-09 11:07 UTC, paneiOS reviewed
코드리뷰 남겼습니다.

init 대신 함수로 만들고자 했던 이유가 init이 틀려서 말씀드렸던건 아니고 데이터가 고정이 아니라면 함수를 이용해야하는데 그부분을 설명하고자 저번 리뷰에 코멘트를 달았었습니다..

오늘 코멘트보시면 init이랑 뭐가달라라는 말이 나올것같아서 약간 후회되네요ㅎㅎ...🥲

2024-05-09 11:08 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    required init?(coder: NSCoder) {
왜 답변 안달아줘요...🤔

2024-05-09 13:06 UTC, qwe179 reviewed
코멘트 이제 보이실까요???

2024-05-09 13:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +            $0.leading.equalToSuperview()
centerY 와 leading 는 성격이 달라서 . 연산자가 사용이 안 될 줄 알았는데 이렇게도 사용가능하군요!!

2024-05-09 13:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +            $0.width.height.equalTo(24)
width.height 를 size 로 간략하게 줄여 쓸 수 있다는 것을 처음 알았네요! 이런 꿀팁을 알려주셔서 감사해요!

2024-05-09 13:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +            $0.trailing.equalTo(-15)
inset 을 사용하면  리딩과 트레일링을 따로 잡지 않아도 superView 기준에서 안쪽여백 15로 한번에 잡을 수 있네요!!

2024-05-09 13:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +        nextButton.addTarget(self, action: #selector(goNextView), for: .touchUpInside)
ReactorKit 을 사용하지 않고도 RxCocoa로 연결할 수 있다는 사실을 잊고 있었습니다. RxCocoa를 사용하여 연결하니 objc 함수를 사용하지 않고도 버튼을 연결할 수 있었습니다.

2024-05-09 13:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +//  ViewController.swift
🤣코드를 붙여넣기 하다보니 실수하였습니다. 변경하였습니다.

2024-05-09 13:06 UTC, qwe179 commented on RunToYou/AppDelegate.swift
> -
swiftLint 에 기본적으로 들어가는 룰들은 .swiftlint 파일에서 따로 적용을 하지 않아도 적용되는 규칙들입니다.
이런 규칙들의 예시로는 file_length, void_return, trailing_whitespace 등이 있으며,
 SwiftLint github 에 잘 정리되어 있습니다. 
 
 위에서 라인을 지운 이유는 trailing_whitespace 룰에 위배되기 때문이었는데, 여백만 지우면 문제 될 것이 없는 부분이었습니다. swiftLint의 사용법에 대해 자세하게 알았고,
  팀원들간 합의 하에 새로운 규칙을 넣어보는 것도 좋을 것 같습니다.😃

2024-05-09 13:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +    required init?(coder: NSCoder) {
스토리보드나 xib 를 통해서 뷰를 구성할 때는  required init?(coder: NSCoder) 이 호출되야 하는데, 우리는 코드를 통해서 뷰를 생성하고 있기 때문에 required init?(coder: NSCoder) 이 호출되면 앱이 종료되고 맙니다. 
지정생성자를 구현을 하지 않게되면 부모클래스의 생성자가 자동상속되기 때문에 required init?(coder: NSCoder)이 자동상속되지만 코드로 노출되지 않습니다. 
빠네님 말씀대로 init대신 function 에 구현하게되면 확장성과 안정성이 더 좋아질 것 같습니다.

2024-05-09 13:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +    required init?(coder: NSCoder) {
required init?(coder: NSCoder) 안에도 지정생성자에서 사용한 함수를 넣어줘야 스토리보드에 뷰를 연결하더라도 같은 동작을 할 수있는 것 같습니다. 제가 잘못 이해한 거라면 답변 부탁드립니다.

2024-05-09 13:06 UTC, qwe179 commented on RunToYou/Extensions/UIFontExtension.swift
> +    static func attributedTextWithTwoFonts(text1: String, font1: UIFont, text2: String, font2: UIFont) -> NSAttributedString {
더이상 사용할 함수는 아니라서 말씀하신대로 제거하였습니다.

2024-05-09 13:06 UTC, qwe179 commented on RunToYou/Extensions/UIColorExtension.swift
> +    static func getColor(hexString: String, alpha: CGFloat = 1.0) -> UIColor {
rgba 로 바로 볼수있는 새로운 사실을 알았네요!!😂 지금껏 hexstring으로만 쓰고 있었습니다.

2024-05-09 13:23 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    required init?(coder: NSCoder) {
이거 왜달려있쥐...😓

2024-05-09 13:25 UTC, paneiOS commented on RunToYou/AppDelegate.swift
> -
팀원들간 합의 하에 새로운 규칙을 넣어보는 것도 좋을 것 같습니다. GPT 냄새가 납니다?;;😱

2024-05-09 13:29 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    required init?(coder: NSCoder) {
fatalError이 들어가있는데 물론 이 함수가 호출될일이 없기야하겠지만 fatalError보다는 super.init이나 setupLayout()을 넣어주면 init과 동일한 기능을 하는형태가 되지않을까 생각이 듭니다.

2024-05-09 13:51 UTC, qwe179 commented on RunToYou/AppDelegate.swift
> -
이거 gpt 가 아니라 제가 쓴건데용 ㅠㅠ 답변 잘 써서 gpt 느낌이 났나요?? gpt 한테도 사실 물어봤는데 걔는 디폴트로 적용되는거 없다고하더라구요. gpt 한테 말투 옮았는지도~~

2024-05-10 07:06 UTC, qwe179 reviewed
수정할수있는 부분 수정했는데, 잘못된 부분 있으면 말씀주세요😄

2024-05-10 07:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +    private func setAddTarget() {
코딩 컨벤션에 따라야죠~ setup으로 사용하도록 하겠습니다🤣

2024-05-10 07:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +    private func setupLayout() {
setupLayout 위에 말씀하신건가요?? 한칸띄워놓겠습니다~

2024-05-10 07:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +        }
if !isOptional { self.optionalLabel.isHidden = true } 과 같은 형태 또는 삼항연산자로 쓸 수 있을 것 같습니다.🤔
이런 경우는, 삼항연산자보다는 if 문으로 쓰는게 가독성 측면에서는 나아보입니다.

2024-05-10 07:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +    deinit {
deinit 이 마지막에 실행되기때문에 끝쪽에 놨습니다. 듣고보니 deinit 이 init 쪽에 같이 있는게 보기 편하겠네요~ 😁

2024-05-10 07:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +    private func goNextView() {
네..... 잊고있었습니다. 하는김에 코드 스니펫에도 추가했습니다. TODO에 있는 항목을 처리하지 않으면 todo 워닝이 뜨네요. 만약에 개발을 하면 TODO 주석을 지우면 되나요??

2024-05-10 07:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +                self?.goNextView()
네 저번에 말씀하셨던 내용인데 사실 guard 문을 써야하는 정확한 이유를 모르겠습니다. guard 문 처리를 하는것과 안하는 것의 차이가 무엇인가요??🤔

2024-05-10 07:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +        setupDatas()
멍청했습니다 제가

2024-05-10 07:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +        recordRowView.setupDatas(
선언시에 클로저 내에서 처리를 할 수 있었네요!! 코드가 더 깔끔해졌습니다.

2024-05-10 07:06 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +    private let disposeBag = DisposeBag()
제 생각엔 UI 프로퍼티가  UI가 아닌 프로퍼티보다 훨씬 많을 것 같으니,
UI가 아닌 프로퍼티를 처음에 두고, UI 프로퍼티를 배치, 그 밑에 viewDodLoad, init, 메서드 순으로 배치하는 것은 어떠실지요?

2024-05-10 07:06 UTC, qwe179 commented on RunToYou/SceneDelegate.swift
>          window.rootViewController = UINavigationController(rootViewController: viewController)
네비게이션을 사용하지 않는 화면에서는 hidden 처리하면 될것같아 그냥 두었습니다. 나중에 네비게이션을 사용할때 네비게이션의 루트뷰컨트롤러를 지정해줘야할텐데,  화면 넘어가는 코드에서 처리하는것보다 SceneDelegate 에서 처음에 설정해 두는게 번거롭지 않을 것 같다는 생각이었습니다.

2024-05-10 11:38 UTC, paneiOS commented on RunToYou/AppDelegate.swift
> -
예전에는 기본룰이 없었는데 최근 버전에 기본룰 적용이 생긴것같더라구요. gpt가 2년전 기준이라 그럴수있습니다.

2024-05-10 11:41 UTC, paneiOS commented on RunToYou/SceneDelegate.swift
>          window.rootViewController = UINavigationController(rootViewController: viewController)
음 글쎄요 나중에 rootVC에 네비게이션을 쓰는건 확실한가요?
로직상 메인은 TabBarVC로 보이는데 TabBarVC도 네비를 넣어서 노출시킨다는 뜻인가요? TabBarVC도 보면 네비가 있어보이진 않던데요?

2024-05-10 11:45 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    private let disposeBag = DisposeBag()
제 생각은 많아서 오히려 위로 올리는게 맞지 않을까 싶습니다.
우선 UI로직을 먼저 만들것으로 보이는데 이후 함수를 만들때 UI프로퍼티를 추가하면서 만드는경우보다 함수에따라 필요한 프로퍼티들을 추가할것같습니다.
그런데 추가할때마다 UI프로퍼티들 위에 선언한다는건 많은만큼 스크롤을 올려야된다는 뜻아닐까요?

2024-05-10 11:46 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    private func setAddTarget() {
set은 지양한다고 되어있지는 않습니다. 여쭤본것입니다ㅎㅎ

2024-05-10 11:48 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +                self?.goNextView()
우선 self 뒤 ?가 왜 들어가는지에 대해 혹시 아시나요?

[weak self]를 사용할경우 옵셔널로 구현해야하는게 핵심인데 휴면에러로 `?`를 못넣을경우 리뷰하는 입장에서도 발견하기가 힘들고 구현하는 사람도 놓칠수 있기 때문에 guard문으로 옵셔널을 제거하는 라인을 눈에 보이게 추가하자는 뜻입니다.

2024-05-10 11:50 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +    private func goNextView() {
네 스위프트린트 룰에 주석을 쓰지말라는게 있는데 Todo주석은 어차피 잊지않고 하기위한것이니까 워닝으로 보여도 괜찮을것같습니다.
todo주석은 지울예정이라 괜찮습니다.

2024-05-10 11:54 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +        }
저런 if문은 저희의 코딩 컨벤션에 적합하지 않으니 오답입니다.
삼항연산자도 하나의 방법일수있지만 가독성을 생각하면 역시 오답입니다.

한번만 더 생각해봐주세요.

다음 코멘트에는 답을 알려드리겠습니다.
힌트는 조건문이 필요없습니다.

2024-05-10 11:55 UTC, paneiOS commented
코멘트 중복이어서 hide 처리했습니다.
일부 resolve conversation 처리 해주시고 답변 안달린것도 하나 있었으니 확인 부탁드립니다.

2024-05-13 05:20 UTC, qwe179 reviewed
코멘트 답변, 커밋 완료했습니다.

2024-05-13 05:20 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +        }
조건문도 아니고 삼항연산자도 아니라면 self.optionalLabel.isHidden = !isOptional 라고 쓰는게 정답일 것 같네요.
어짜피 Bool 타입으로 들어가는거니 조건문이 애초에 필요가 없었네요!😭

2024-05-13 05:20 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +    func setupDatas(image: UIImage, titleString: String, detailString: String, isOptional: Bool) {
기본값을 넣어주면 각각 true 로 셋팅해줄 필요가 없었겠네요

2024-05-13 05:20 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +    private func goNextView() {
todo 주석을 미리  설정 해놓으면 까먹지 않겠네요 ㅎㅎ

2024-05-13 05:20 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +                self?.goNextView()
self 는 AppAuthViewController 인데, weak 으로 캡처했기 때문에, nil 이 될수도 있기 때문에 self 뒤에 ? 를 붙여줘야 안전하게 접근할 수 있을것같습니다. guard 문으로 헷깔리지 않게 휴먼에러를 방지하자는 말씀이군요. 좋은 생각입니다.

2024-05-13 05:20 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +    private let disposeBag = DisposeBag()
그것도 그렇네요, 저는 정리적인 측면에서 그렇게 생각했고, 효율적인 측면에서는 생각해보지 않았던 것 같습니다. 프로퍼티 추가할때 스크롤 올리면서 불편했던적이 저도 있어서, 이렇게 해보면 좋을것 같네요

2024-05-13 05:20 UTC, qwe179 commented on RunToYou/SceneDelegate.swift
>          window.rootViewController = UINavigationController(rootViewController: viewController)
아 저희 탭뷰가 있었죠.. 바꾸겠습니다..

2024-05-13 05:20 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +    private func setAddTarget() {
set 도 get 이랑 같은 성격이니 지양하는게 좋을것같습니다~

2024-05-14 11:20 UTC, paneiOS commented on RunToYou/Extensions/UIColorExtension.swift
> +
UIFontExtension 문서는 여기 한칸 안띄어쓰셨는데 여기도 붙이는게 어떨까요?
앞으로 class나 extension 바로 아래는 붙여쓰는게 좋을것같습니다.

2024-05-14 11:22 UTC, paneiOS commented on RunToYou/Extensions/UIColorExtension.swift
> +//  UIColorExtension.swift
보통 파일이름을 UIColor+Extension으로 짓는데 저는 UIColor+까지만 하는걸 선호하는데 이유는 어차피 Extensions폴더에 넣기도하고 +가 붙은것만으로도 이건 extension파일이라는걸 인지할수있기때문입니다. 추가로 해당 Extension의 특정기능을 크게 만들어 다시 분리하더라도 +기능 식으로 만들면 되기때문에 확장성도 있습니다.

파일이름을 변경해도 괜찮을까요?

`타입+Extension - 가장 일반적인 방법입니다. 예를 들어, UIColor를 확장하는 경우 파일 이름을 UIColor+Extensions.swift라고 합니다. 이 방식은 어떤 타입의 확장인지 바로 알 수 있어 매우 명확합니다. -gpt`

2024-05-14 11:25 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +        label.text = "* 권한을 허용하지 않아도 앱 이용이 가능하지만 \n 일부 서비스가 제한될 수 있습니다"
`\n`사이의 공백이 필요한 이유가 있을까요?

2024-05-14 11:26 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +        btn.layer.cornerRadius = 7
이거 8 아닌가요?

2024-05-14 11:29 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +            $0.top.equalToSuperview().inset(140)
이거 디바이스 화면에 따라 다른 뷰하고 간격이 일정하지 않을것같아보이는데 혹시 테스트 해보셨나요?

2024-05-14 11:32 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +         label.text = " (선택)"
" "을 텍스트로 간격을 주셨는데 Label 사이에 간격을 주지 않고 띄어쓰기 하신 이유가 있나요?

2024-05-14 11:34 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +            $0.leading.equalTo(titleLabel.snp.trailing).offset(3)
음? 여기 여백이 있네요? 위에서 공백을 String으로 넣은 이유가 궁금해지네요

2024-05-14 11:36 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +
제거했으면 하는 마음

2024-05-14 11:42 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +                self.goNextView(isPresent: isPresent)
isPresent를 goNextView에 전달할 이유가 없어보입니다. 그냥 true인 경우만 통과시키면 되지 않나요? 아니면 다른 용도가 있나요?

2024-05-14 11:43 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +            newState.albumAuthResult = status
여기서 상태변화만 시키고 이후 어떤 행동을 하진 않아보이는데 아닌가요?

2024-05-14 11:50 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +                }, Observable.just(Mutation.goNextPage)])
여기도 함수로 쪼개서 기능을 분리하고 concat으로 합친것만 보이게 하는게 가독성이 좋을것같습니다.

2024-05-14 11:56 UTC, paneiOS commented
제가 알기로는 안내화면 말그대로 안내일뿐 여기서 다음을 누른다고 어떤 권한에 대한 요청이 뜨는건 다른 이야기라고 생각합니다.

물론 여기 있어도 되지만 실제로 구현되면 다음버튼을 눌렀을때 시스템 팝업들이 3개~4개가 노출되는데 이때 동의 여부와 상관없이 다 확인을 받고나서 이동되게 되는게 좋은 로직인지는 잘 모르겠습니다.
아니면 화면 노출과 동시에 띄우는게 더 낫지않나 싶고 그게 꼭 여기 화면일 필요는 없다 생각이 듭니다. 지금 방법이 잘못됐다는이야기가 아니라 이런것들을 고려한다음 의도했는지가 궁금합니다.

2024-05-14 12:04 UTC, qwe179 commented on RunToYou/Extensions/UIColorExtension.swift
> +
확인 했습니다. 저도 통일하는게 좋을 것 같다고 생각하고 있었습니다.

2024-05-14 12:09 UTC, qwe179 commented on RunToYou/Extensions/UIColorExtension.swift
> +//  UIColorExtension.swift
네 괜찮습니다. +Extension 라고 이름짓는걸 몇 번 봤는데, 일반적으로 그렇게 많이 짓나보네요. 파일명 변경하겠습니다.

2024-05-14 12:13 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +        label.text = "* 권한을 허용하지 않아도 앱 이용이 가능하지만 \n 일부 서비스가 제한될 수 있습니다"
아뇨 필요없는데 넣은 것 같습니다😂

2024-05-14 12:13 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +        btn.layer.cornerRadius = 7
피그마 보니 8이네요. 피그마에서 확인할 수 있단 사실을 처음 알았네요..

2024-05-14 13:11 UTC, paneiOS commented on RunToYou/Extensions/UIColorExtension.swift
> +//  UIColorExtension.swift
넵 저희는 UIColor+ 이렇게만 하도록하죠!

2024-05-17 03:57 UTC, qwe179 reviewed
뷰 쪽 snapkit 과 reactor 코드들 수정했습니다. 확인부탁드려요~😎

2024-05-17 03:57 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +            $0.top.equalToSuperview().inset(140)
노치에 따라 간격이 달라질 수 있군요. 
찾아보니  $0.top.equalToSuperview().inset(140) 으로 간격을 주면 상단 노치를 고려하지 않은 간격으로 들어가고, view.safeAreaLayoutGuide 를 사용하면 노치를 제외한 safearea 높이만큼 떨어뜨릴 수 있다고 하네요.
후자처럼 바꾸자는 말씀이시죠?

2024-05-17 03:57 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +         label.text = " (선택)"
아뇨. 코드 시험 해보고 제거하지 않은 것 같습니다. 수정하겠습니다.

2024-05-17 03:57 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +            $0.leading.equalTo(titleLabel.snp.trailing).offset(3)
저도 궁금하네요 😂 위에 공백 수정하면서 같이 수정했습니다.

2024-05-17 03:57 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +
공백 말씀 하시는거군요. 확인 잘하겠습니다.

2024-05-17 03:57 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +                self.goNextView(isPresent: isPresent)
goNextView 까지 전달할 필요는 없었고, .filter { $0 == true } 사용해서 통과시키면 되겠네요.

2024-05-17 03:57 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +                }, Observable.just(Mutation.goNextPage)])
메서드로 빼니까 가독성과 확장성이 늘어났네요. 메서드로 빼는 연습을 많이 해야겠습니다.

2024-05-17 03:57 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +            newState.albumAuthResult = status
나중에 결과값을 처리할 일이 있을까 미리 만들어 놨는데, 어제말씀하신대로 어떻게 될지 모르는데 미리 개발할 필요는 없고, 쓰지도 않을 것 같네요. 삭제 처리했습니다.

2024-05-17 10:47 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +                self.goNextView(isPresent: isPresent)
`== true`는 없어도 됩니다.

2024-05-17 10:50 UTC, paneiOS commented on RunToYou/AppAuth/AppAuthViewController.swift
> +            $0.top.equalTo(view.safeAreaLayoutGuide).offset(140)
140이 아닐것같은 예감...

2024-05-17 10:53 UTC, paneiOS commented on RunToYou/View/AppAuthViewController.swift
> +                self.goNextView(isPresent: isPresent)
== true는 없어도 됩니다.

2024-05-18 00:20 UTC, qwe179 reviewed
ㅠㅠ 몇가지 생각못했던게 나오네요 더 계속 꼼꼼하게 확인해봐야겠습니다.

2024-05-18 00:20 UTC, qwe179 commented on RunToYou/View/AppAuthViewController.swift
> +                self.goNextView(isPresent: isPresent)
전혀 필요없는 코드였군요..

2024-05-18 00:20 UTC, qwe179 commented on RunToYou/AppAuth/AppAuthViewController.swift
> +            $0.top.equalTo(view.safeAreaLayoutGuide).offset(140)
세이프레이아웃가이드 높이를 생각 못했네요.. 피그마 확인해보니 93이었습니다.

2024-05-19 10:12 UTC, paneiOS requested changes
수고하셨습니다.

다만 한가지 궁금한게 있는데요.

requestLocationAuth()의 경우에는 .goNextPage로 리턴되잖아요?

requestNotificationAuth를 포함한 3가지 함수가 모두 Observable<Mutation>으로 리턴되는 함수인데 어떤 .onNext가 없는데 뭘로 리턴되죠???

2024-05-19 12:57 UTC, qwe179 commented
리턴되는건 없는걸로 알고있습니다. 순차적으로 실행만하고 각각의 결과에 대한 리턴은 없올거에요. concat 으로 묶었으니 결국엔 .goNextPage 가 리턴 되겠네요

2024-05-19 13:11 UTC, paneiOS commented
> 리턴되는건 없는걸로 알고있습니다. 순차적으로 실행만하고 각각의 결과에 대한 리턴은 없올거에요. concat 으로 묶었으니 결국엔 .goNextPage 가 리턴 되겠네요

리턴되는게 없을수가 있나요? 물론 컴파일러 에러가 없으니까 가능은 하겠지만 Mutation으로 케이스를 만들었는데 거기에 해당하지 않는 케이스에 어떤 형식으로 오지 않을까요? 콘솔에 찍어 보셨나요?

2024-05-19 13:53 UTC, qwe179 commented
리턴 형식은 Mutation 이지만 .onNext 는 따로 지정해주지않아 리턴값은 없고 . 함수의 비동기 처리가 끝나면 onComplete 가 호출되어 종료되버리네요
requestNotificationAuth().subscribe(onNext: { param in
                print("param : ",param)
            }) 이런식으로 찍어봐도 "param : " 조차 안찍힙니다.

2024-05-19 13:58 UTC, paneiOS commented
아 그러면 그냥 멈추겠네요.
사실상 저 함수들은 작동하지 않는 함수로 볼수있겠군요

2024-05-19 13:59 UTC, paneiOS approved these changes
코멘트 100개로 끝났군요.
이후 제 PR도 서로를 위해 이렇게 공격적으로(멘트가 아닌 코드리뷰를) 부탁드립니다.
수고하셨습니다.

2024-05-20 01:56 UTC, merged